declare module 'swapsicle-contract-addresses' {
  export const ChainId: {
    ETHEREUM: number;
    OPTIMISM: number;
    MATIC: number;
    MATIC_TESTNET: number;
    FANTOM: number;
    FANTOM_TESTNET: number;
    BSC: number;
    BSC_TESTNET: number;
    ARBITRUM: number;
    ARBITRUM_TESTNET: number;
    HECO: number;
    HECO_TESTNET: number;
    HARMONY: number;
    HARMONY_TESTNET: number;
    OKEX: number;
    OKEX_TESTNET: number;
    HARDHAT: number;
    AVALANCHE: number;
    AVALANCHE_TESTNET: number;
    MANTLE: number;
    MANTLE_TESTNET: number;
    TELOS: number;
    TELOS_TESTNET: number;
    TAIKO: number;
    TAIKO_TESTNET: number;
  };

  export const POPS_ADDRESS: Record<number, string>;
  export const USDC_ADDRESS: Record<number, string>;
  export const USDT_ADDRESS: Record<number, string>;
  export const WNATIVE_ADDRESS: Record<number, string>;
  export const DAI_ADDRESS: Record<number, string>;
  export const FACTORY_ADDRESS: Record<number, string>;
  export const ROUTER_ADDRESS: Record<number, string>;
  export const ICECREAMVAN_V2_ADDRESS: Record<number, string>;
  export const ICECREAMVAN_V2_ADDRESS_OLD: Record<number, string>;
  export const COMMUNITY_VAULT_ADDRESS: Record<number, string>;
  export const ZOMBIEVAN_ADDRESS: Record<number, string>;
  export const BENTOBOX_ADDRESS: Record<number, string>;
  export const BORING_HELPER_ADDRESS: Record<number, string>;
  export const ENS_REGISTRAR_ADDRESS: Record<number, string>;
  export const MERKLE_DISTRIBUTOR_ADDRESS: Record<number, string>;
  export const MULTICALL2_ADDRESS: Record<number, string>;
  export const SLUSH_ADDRESS: Record<number, string>;
  export const ICE_ADDRESS: Record<number, string>;
  export const ICECREAMZOMBIES_NFT_ADDRESS: Record<number, string>;
  export const STLOSTOKEN_ADDRESS: Record<number, string>;
  export const NATIVE_PAYMENT_TOKEN: Record<number, string>;
  export const BRIDGE_V2_CONTRACT: Record<number, string>;
  export const V3_POOL_INIT_CODE_HASH: Record<number, string>;
  export const V3_ALGEBRA_FACTORY_ADDRESS: Record<number, string>;
  export const V3_ALGEBRA_POOL_DEPLOYER_ADDRESS: Record<number, string>;
  export const V3_ALGEBRA_QUOTER_ADDRESS: Record<number, string>;
  export const V3_SWAP_ROUTER_ADDRESS: Record<number, string>;
  export const V3_NONFUNGIBLE_POSITION_MANAGER_ADDRESS: Record<number, string>;
  export const V3_MULTICALL_ADDRESS: Record<number, string>;
  export const V3_OLD_FARMING_CENTER_ADDRESS: Record<number, string>;
  export const V3_FARMING_CENTER_ADDRESS: Record<number, string>;
  export const V3_ETERNAL_FARMING_ADDRESS: Record<number, string>;
}